/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PurchaseRole;

import Business.Enterprise.Enterprise;
<<<<<<< HEAD
import Business.Organization.PurchaseOrganization;
import Business.UserAccount.UserAccount;
=======
import Business.Network.Network;
import Business.Organization.PurchaseInventory;
import Business.Organization.PurchaseOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.requestVaccine;
import java.awt.CardLayout;
>>>>>>> parent of f88db4b... All WR done
import javax.swing.JPanel;

/**
 *
 * @author vraj
 */
public class PurchaseWorkAreaJPanel extends javax.swing.JPanel {
        
    private JPanel userProcessContainer;
    private PurchaseOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form DistributionWorkAreaJPanel
     */
    public PurchaseWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, PurchaseOrganization organization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
<<<<<<< HEAD
        
=======
        populateTable();
>>>>>>> parent of f88db4b... All WR done
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPurchase = new javax.swing.JButton();

        setBackground(new java.awt.Color(36, 47, 65));
        setMinimumSize(new java.awt.Dimension(1440, 848));
        setPreferredSize(new java.awt.Dimension(1440, 848));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Purchase Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 46, -1, -1));

        btnPurchase.setText("Place Purchase Order");
        add(btnPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 749, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPurchase;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
<<<<<<< HEAD
=======

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) vaccineTable.getModel();
        model.setRowCount(0);
        try{
        for(WorkRequest rv:userAccount.getWorkQueue().getWorkRequestList()){
            Object row[] = new Object[4];
            row[0] = rv;
            row[1] = pi.getQty();
            model.addRow(row);
        }
        }
        catch(NullPointerException e){
            System.out.println("No records found");
        }
    }
>>>>>>> parent of f88db4b... All WR done
}
