/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PersonRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.PersonOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.appointment;
import Business.WorkQueue.prescribeMedicine;
import Business.WorkQueue.vaccinate;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abhis
 */
public class PersonWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonWorkAreaJPanel
     */
     private JPanel userProcessContainer;
     private UserAccount account;
     private PersonOrganization organization;
     private Enterprise enterprise;
     private EcoSystem business;
     private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
     private Date v1date;
    
    public PersonWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, PersonOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        populateVaccineTable();
        populateAppointmentTable();
        populateMedTable();
        Date td = new Date();
        lblValue.setText(account.getEmployee().getName());
//        System.out.println(((td.getTime()-v1date.getTime())/(1000*60*60*24))%365);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        btnVaccine = new javax.swing.JButton();
        btnAppointment = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVaccineRequest = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAppoinment = new javax.swing.JTable();
        cardWorkArea = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        setBackground(new java.awt.Color(36, 47, 65));
        setMinimumSize(new java.awt.Dimension(1440, 848));
        setPreferredSize(new java.awt.Dimension(1440, 848));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVaccine.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        btnVaccine.setText("Schedule Vaccination");
        btnVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaccineActionPerformed(evt);
            }
        });
        add(btnVaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        btnAppointment.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        btnAppointment.setText("Schedule Appointment");
        btnAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointmentActionPerformed(evt);
            }
        });
        add(btnAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 740, -1, -1));

        tblVaccineRequest.setBackground(new java.awt.Color(97, 212, 195));
        tblVaccineRequest.setForeground(new java.awt.Color(36, 47, 65));
        tblVaccineRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sender", "Vaccination Date", "Status", "Distribution Center", "Vaccine Name"
            }
        ));
        tblVaccineRequest.setGridColor(new java.awt.Color(97, 212, 195));
        tblVaccineRequest.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblVaccineRequest.setRowHeight(20);
        jScrollPane2.setViewportView(tblVaccineRequest);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 610, 180));

        tblAppoinment.setBackground(new java.awt.Color(97, 212, 195));
        tblAppoinment.setForeground(new java.awt.Color(36, 47, 65));
        tblAppoinment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sender", "Receiver", "Status", "Date"
            }
        ));
        tblAppoinment.setGridColor(new java.awt.Color(97, 212, 195));
        tblAppoinment.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblAppoinment.setRowHeight(20);
        jScrollPane1.setViewportView(tblAppoinment);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 410, 180));

        cardWorkArea.setBackground(new java.awt.Color(36, 47, 65));
        cardWorkArea.setMinimumSize(new java.awt.Dimension(670, 848));
        cardWorkArea.setPreferredSize(new java.awt.Dimension(670, 848));
        cardWorkArea.setLayout(new java.awt.CardLayout());
        add(cardWorkArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, -1));

        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PERSONWORKAREA.png"))); // NOI18N
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 0, 100, 850));

        lblValue.setFont(new java.awt.Font("Optima", 1, 22)); // NOI18N
        lblValue.setForeground(new java.awt.Color(97, 212, 195));
        lblValue.setText("<value>");
        add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 230, 30));

        lblText.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        lblText.setForeground(new java.awt.Color(255, 255, 255));
        lblText.setText("Currently Logged in as:");
        add(lblText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaccineActionPerformed
        // TODO add your handling code here:
        int count = tblVaccineRequest.getModel().getRowCount();
        if(count==0){
        populateVaccineTable();
        ScheduleVaccineJPanel scheduleVaccineJPanel = new ScheduleVaccineJPanel(userProcessContainer, organization, enterprise, business, account);
        cardWorkArea.add("scheduleVaccineJPanel", scheduleVaccineJPanel);
        CardLayout layout = (CardLayout) cardWorkArea.getLayout();
        layout.next(cardWorkArea);
        dB4OUtil.storeSystem(business);
        }
        else{
            JOptionPane.showMessageDialog(this, "You already have a vaccination request submitted");
            return;
        }
    }//GEN-LAST:event_btnVaccineActionPerformed

    private void btnAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentActionPerformed
        // TODO add your handling code here:
        int count = tblVaccineRequest.getModel().getRowCount();
        if(count!=0){
        populateAppointmentTable();
        ScheduleAppointmentJPanel scheduleAppointmentJPanel = new ScheduleAppointmentJPanel(userProcessContainer, organization, enterprise, business, account);
        cardWorkArea.add("scheduleAppointmentJPanel", scheduleAppointmentJPanel);
        CardLayout layout = (CardLayout) cardWorkArea.getLayout();
        layout.next(cardWorkArea);
        }
        else{
            JOptionPane.showMessageDialog(this, "You can only book an appointment if you have received or a vaccination scheduled!!");
            return;
        }
    }//GEN-LAST:event_btnAppointmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PharmajTable;
    private javax.swing.JButton btnAppointment;
    private javax.swing.JButton btnVaccine;
    private javax.swing.JPanel cardWorkArea;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValue;
    private javax.swing.JTable tblAppoinment;
    private javax.swing.JTable tblVaccineRequest;
    // End of variables declaration//GEN-END:variables

    private void populateVaccineTable() {
        DefaultTableModel model = (DefaultTableModel) tblVaccineRequest.getModel();
        model.setRowCount(0);
        System.out.println("out for");
        for(WorkRequest wr : account.getWorkQueue().getWorkRequestList()){
           Object[] row = new Object[5];
           
        System.out.println("in for");
           if(wr instanceof vaccinate){
               
        System.out.println("wr found");
           String Date = ((vaccinate) wr).getDate();
           
               
        System.out.println("in try");
               
        System.out.println("in if");
           row[0] = wr;
           
           row[1] = Date;
           
//           row[1] = null;
           row[2] = wr.getStatus();
           v1date = ((vaccinate) wr).getDt();
           System.out.println(v1date);
           Date td = new Date();
//           System.out.println(((td.getTime()-v1date.getTime())/(1000*60*60*24))%365);
           String dc = ((vaccinate) wr).getDistributionCenter();
           row[3] = dc;
           row[4] = null;
           model.addRow(row);
        
       
    }
        }
    }

    private void populateAppointmentTable() {
        DefaultTableModel model = (DefaultTableModel) tblAppoinment.getModel();
        model.setRowCount(0);
        
        for(WorkRequest wr : account.getWorkQueue().getWorkRequestList()){
           Object[] row = new Object[4];
           if(wr instanceof appointment){
           String hospitalName = ((appointment) wr).getHospitalName();
           if(hospitalName.length()!=0){
           row[0] = wr;
           String Date = ((appointment) wr).getDate();
           row[1] = hospitalName;
           row[2] = wr.getStatus();
           row[3] = Date;
           
           model.addRow(row);
           }
        }
        }
    }

    private void populateMedTable() {
        DefaultTableModel model = (DefaultTableModel)PharmajTable.getModel();
        model.setRowCount(0);
        
        for(WorkRequest wr : account.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            if(wr instanceof prescribeMedicine){
                row[0] = wr;
                row[1] = wr.getSender();
                row[2] = wr.getReceiver();
                row[3] = ((prescribeMedicine) wr).getMedList();
                row[4] = wr.getStatus();
                model.addRow(row);
                
            }
        }
    }
}
