/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PersonRole;
import Business.Validation;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Organization.PersonOrganization;
import Business.Organization.PurchaseOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.appointment;
import Business.WorkQueue.vaccinate;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author abhis
 */
public class ScheduleAppointmentJPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private PersonOrganization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private UserAccount userAccount;
    private Validation validation;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    /**
     * Creates new form ScheduleAppointmentJPanel
     */
    public ScheduleAppointmentJPanel(JPanel userProcessContainer, PersonOrganization organization, Enterprise enterprise, EcoSystem business, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.organization = organization;
        this.enterprise = enterprise;
        populateOrganizationComboBox();
    }

    public void populateOrganizationComboBox(){
        HospitaljComboBox.removeAllItems();
        
        Network currnet = enterprise.getNetwork();
        for(Enterprise e: currnet.getEnterpriseDirectory().getEnterpriseList()){
        if(e.getEnterpriseType() == Enterprise.EnterpriseType.Hospital){
            HospitaljComboBox.addItem(e.getName());
//            currEP = e;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        HospitaljComboBox = new javax.swing.JComboBox<>();
        btnRequestAppointment = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        separatorLine = new javax.swing.JSeparator();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(36, 47, 65));
        setMinimumSize(new java.awt.Dimension(1440, 848));
        setPreferredSize(new java.awt.Dimension(1440, 848));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Hospital:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 56, -1, -1));

        HospitaljComboBox.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        HospitaljComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(HospitaljComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 52, -1, -1));

        btnRequestAppointment.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        btnRequestAppointment.setText("Request");
        btnRequestAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestAppointmentActionPerformed(evt);
            }
        });
        add(btnRequestAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter your Email:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        txtEmail.setBackground(new java.awt.Color(36, 47, 65));
        txtEmail.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 290, 30));

        separatorLine.setForeground(new java.awt.Color(255, 255, 255));
        separatorLine.setMinimumSize(new java.awt.Dimension(1, 12));
        separatorLine.setPreferredSize(new java.awt.Dimension(1, 12));
        add(separatorLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 280, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestAppointmentActionPerformed
        // TODO add your handling code here:
        if(!validation.emailValidator(txtEmail.getText())){
            JOptionPane.showMessageDialog(this, "Please enter a valid email");
            return;
        }
        appointment v = new appointment();
        UserAccount receiver = new UserAccount();
        if(jComboBox1.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "Please select a hospital to request vaccination");
            return;
        }
        v.setHospitalName(jComboBox1.getSelectedItem().toString());
        v.setPerson(userAccount);
        v.setSender(userAccount);
        v.setStatus("Requested");
        v.setEmail(txtEmail.getText());
        v.setMessage(userAccount.getUsername());
       
        Network currNet = enterprise.getNetwork();
        
        for(Enterprise e : currNet.getEnterpriseDirectory().getEnterpriseList()){
            System.out.print("1");
            System.out.println(e.getEnterpriseType());
            if(e.getEnterpriseType().toString().equals("Hospital")){
                for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                    for(UserAccount u : o.getUserAccountDirectory().getUserAccountList()){
                        System.out.println("2");
                        System.out.println(u.getRole().toString());
                        System.out.println(u.getUsername());
                        if(u.getRole().toString().equals("Business.Role.DoctorRole")){
                            v.setReceiver(u);
                            receiver = u;
                        }
                    }
                }
            }
        }
//        for(UserAccount u: business.getUserAccountDirectory().getUserAccountList()){
//            System.out.println(u.getUsername());
//            System.out.println(jComboBox1.getSelectedItem().toString());
//            System.out.println(u.getUsername().equals(jComboBox1.getSelectedItem().toString()));
//            if(u.getUsername().equals(jComboBox1.getSelectedItem().toString())){
//               System.out.println(u.getUsername());
//               v.setReceiver(u);
//               receiver = u;
//            }
//        }
        receiver.getWorkQueue().getWorkRequestList().add(v);
        userAccount.getWorkQueue().getWorkRequestList().add(v);
        JOptionPane.showMessageDialog(this, "Request sent");
        dB4OUtil.storeSystem(business);
        txtEmail.setText("");
    }//GEN-LAST:event_btnRequestAppointmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> HospitaljComboBox;
    private javax.swing.JButton btnRequestAppointment;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator separatorLine;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
