/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PersonRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Organization.PersonOrganization;
import Business.Organization.PurchaseOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.appointment;
import Business.WorkQueue.vaccinate;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author abhis
 */
public class ScheduleAppointmentJPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private PersonOrganization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private UserAccount userAccount;
    /**
     * Creates new form ScheduleAppointmentJPanel
     */
    public ScheduleAppointmentJPanel(JPanel userProcessContainer, PersonOrganization organization, Enterprise enterprise, EcoSystem business, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.organization = organization;
        this.enterprise = enterprise;
        populateOrganizationComboBox();
    }

    public void populateOrganizationComboBox(){
        HospitaljComboBox.removeAllItems();
        
        Network currnet = enterprise.getNetwork();
        for(Enterprise e: currnet.getEnterpriseDirectory().getEnterpriseList()){
        if(e.getEnterpriseType() == Enterprise.EnterpriseType.Hospital){
            HospitaljComboBox.addItem(e.getName());
//            currEP = e;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        HospitaljComboBox = new javax.swing.JComboBox<>();
        btnRequestAppointment = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Select Hospital:");

        HospitaljComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRequestAppointment.setText("Request");
        btnRequestAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestAppointmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1)
                        .addGap(90, 90, 90)
                        .addComponent(HospitaljComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnRequestAppointment)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(HospitaljComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(btnRequestAppointment)
                .addGap(80, 80, 80))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestAppointmentActionPerformed
        // TODO add your handling code here:
        appointment v = new appointment();
        UserAccount receiver = new UserAccount();
        if(jComboBox1.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "Please select a hospital to request vaccination");
            return;
        }
        v.setHospitalName(jComboBox1.getSelectedItem().toString());
        v.setPerson(userAccount);
        v.setSender(userAccount);
        v.setStatus("Requested");
        v.setMessage(userAccount.getUsername());
       
        Network currNet = enterprise.getNetwork();
        
        for(Enterprise e : currNet.getEnterpriseDirectory().getEnterpriseList()){
            System.out.print("1");
            System.out.println(e.getEnterpriseType());
            if(e.getEnterpriseType().toString().equals("Hospital")){
                for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                    for(UserAccount u : o.getUserAccountDirectory().getUserAccountList()){
                        System.out.println("2");
                        System.out.println(u.getRole().toString());
                        System.out.println(u.getUsername());
                        if(u.getRole().toString().equals("Business.Role.DoctorRole")){
                            v.setReceiver(u);
                            receiver = u;
                        }
                    }
                }
            }
        }
//        for(UserAccount u: business.getUserAccountDirectory().getUserAccountList()){
//            System.out.println(u.getUsername());
//            System.out.println(jComboBox1.getSelectedItem().toString());
//            System.out.println(u.getUsername().equals(jComboBox1.getSelectedItem().toString()));
//            if(u.getUsername().equals(jComboBox1.getSelectedItem().toString())){
//               System.out.println(u.getUsername());
//               v.setReceiver(u);
//               receiver = u;
//            }
//        }
        receiver.getWorkQueue().getWorkRequestList().add(v);
        userAccount.getWorkQueue().getWorkRequestList().add(v);
        JOptionPane.showMessageDialog(this, "Request sent");
    }//GEN-LAST:event_btnRequestAppointmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> HospitaljComboBox;
    private javax.swing.JButton btnRequestAppointment;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
