/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PersonRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.PersonOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.vaccinate;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author abhis
 */
public class ScheduleVaccineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ScheduleVaccineJPanel
     */
    private JPanel userProcessContainer;
    private PersonOrganization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private UserAccount userAccount;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public ScheduleVaccineJPanel(JPanel userProcessContainer, PersonOrganization organization, Enterprise enterprise, EcoSystem business, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.userAccount = userAccount;
        populateDistCenterComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDistributor = new javax.swing.JLabel();
        btnRequest = new javax.swing.JButton();
        cmbDistributor = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(36, 47, 65));
        setMinimumSize(new java.awt.Dimension(1440, 848));
        setPreferredSize(new java.awt.Dimension(1440, 848));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDistributor.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        lblDistributor.setForeground(new java.awt.Color(255, 255, 255));
        lblDistributor.setText("Select Distribution Center:");
        add(lblDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        btnRequest.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        btnRequest.setText("Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });
        add(btnRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        cmbDistributor.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        cmbDistributor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        vaccinate v = new vaccinate();
        UserAccount receiver = new UserAccount();
        UserAccount health = new UserAccount();
        if(cmbDistributor.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "Please select a distribution center to request vaccination");
            return;
        }
        v.setDistributionCenter(cmbDistributor.getSelectedItem().toString());
        v.setPerson(userAccount);
        v.setSender(userAccount);
        v.setStatus("Requested");
        v.setMessage(userAccount.getUsername());
       
        Network currNet = enterprise.getNetwork();
        
        for(Enterprise e : currNet.getEnterpriseDirectory().getEnterpriseList()){
            System.out.print("1");
            System.out.println(e.getEnterpriseType());
            if(e.getEnterpriseType().toString().equals("Service")){
                for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                    for(UserAccount u : o.getUserAccountDirectory().getUserAccountList()){
                        System.out.println("2");
                        System.out.println(u.getUsername());
                        if(u.getRole().toString().equals("Business.Role.DistributionRole")){
                            System.out.println(u.getUsername());
                            v.setReceiver(u);
                            receiver = u;
                        }
                    }
                }
            }
        }
        for(Enterprise e : currNet.getEnterpriseDirectory().getEnterpriseList()){
            System.out.print("1");
            System.out.println(e.getEnterpriseType());
            if(e.getEnterpriseType().toString().equals("Government")){
                for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                    for(UserAccount u : o.getUserAccountDirectory().getUserAccountList()){
                        System.out.println("2");
                        System.out.println(u.getUsername());
                        if(u.getRole().toString().equals("Business.Role.HealthRole")){
                            v.setHealth(u);
                            health = u;
                            break;
                        }
                    }
                }
            }
        }
//        for(UserAccount u: business.getUserAccountDirectory().getUserAccountList()){
//            System.out.println(u.getUsername());
//            System.out.println(jComboBox1.getSelectedItem().toString());
//            System.out.println(u.getUsername().equals(jComboBox1.getSelectedItem().toString()));
//            if(u.getUsername().equals(jComboBox1.getSelectedItem().toString())){
//               System.out.println(u.getUsername());
//               v.setReceiver(u);
//               receiver = u;
//            }
//        }
        receiver.getWorkQueue().getWorkRequestList().add(v);
        userAccount.getWorkQueue().getWorkRequestList().add(v);
        health.getWorkQueue().getWorkRequestList().add(v);
        JOptionPane.showMessageDialog(this, "Request sent");
        dB4OUtil.storeSystem(business);
    }//GEN-LAST:event_btnRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequest;
    private javax.swing.JComboBox<String> cmbDistributor;
    private javax.swing.JLabel lblDistributor;
    // End of variables declaration//GEN-END:variables

    private void populateDistCenterComboBox() {
        cmbDistributor.removeAllItems();
        
        Network currNet = enterprise.getNetwork();
        for(Enterprise e: currNet.getEnterpriseDirectory().getEnterpriseList()){
        if(e.getEnterpriseType() == Enterprise.EnterpriseType.Service){
            for(Organization o: e.getOrganizationDirectory().getOrganizationList()){
                System.out.println(o.getName());
                for(UserAccount u: o.getUserAccountDirectory().getUserAccountList()){
                    System.out.println(u.getRole().toString());
                    if(u.getRole().toString().equals("Business.Role.DistributionRole")){
                        cmbDistributor.addItem(u.getUsername());
                    }
                }
            }
//            currEP = e;
            }
        }
    }
}
