/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.EconomyRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.EconomyOrganization;
import Business.Organization.Vaccine;
import Business.Organization.VaccineDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.approveVaccine;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vraj
 */
public class EconomyWorkAreaJPanel extends javax.swing.JPanel {
        
    private JPanel userProcessContainer;
    private EconomyOrganization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private UserAccount userAccount;
    private VaccineDirectory directory;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    /**
     * Creates new form DistributionWorkAreaJPanel
     */
    public EconomyWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EconomyOrganization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        this.userAccount = account;
        populateTable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        txtNoDose = new javax.swing.JTextField();
        txtGap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();

        setBackground(new java.awt.Color(36, 47, 65));
        setMinimumSize(new java.awt.Dimension(1440, 848));
        setPreferredSize(new java.awt.Dimension(1440, 848));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnApprove.setText("Approve Vaccine");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 562, -1, -1));

        btnReject.setText("Reject Vaccine");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 562, -1, -1));

        jTextField1.setText("EconomyWorkArea");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 27, -1, -1));

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vaccine Name", "Sender", "Receiver", "Status"
            }
        ));
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 92, -1, 241));

        jLabel1.setText("Quantity per dose(in mg):");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 367, -1, -1));

        jLabel2.setText("Number of doses:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 411, -1, -1));

        jLabel3.setText("Gap between dose(in days):");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 455, -1, -1));

        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 362, 83, -1));
        add(txtNoDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 406, 83, -1));

        txtGap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGapActionPerformed(evt);
            }
        });
        add(txtGap, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 450, 83, -1));

        jLabel4.setText("Price (in USD):");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 499, -1, -1));
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 494, 83, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        
        model.setRowCount(0);
        for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = request;
            row[1] = request.getSender().getEmployee().getName();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[3] = request.getStatus();
            
            model.addRow(row);
        }
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        if(txtGap.getText().equals("") || txtNoDose.getText().equals("") || txtPrice.getText().equals("") || txtQty.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill all fields", "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        approveVaccine request = (approveVaccine)workRequestJTable.getValueAt(selectedRow, 0);
        
        if(request.getStatus().equals("Approved")){
            JOptionPane.showMessageDialog(this, "Vaccine already approved");
            return;
        }
     
        if(validate(txtQty.getText(),txtNoDose.getText(),txtGap.getText(),txtPrice.getText())){
        request.setStatus("Approved");
        request.getVaccine().setStatus("Approved");
        
        request.getVaccine().setMgQty(txtQty.getText());
        request.getVaccine().setNoOfDoses(Integer.parseInt(txtNoDose.getText()));
        request.getVaccine().setGap(Integer.parseInt(txtGap.getText()));
        request.getVaccine().setPrice(Double.parseDouble(txtPrice.getText()));
        populateTable();
        }
        dB4OUtil.storeSystem(system);
        txtGap.setText("");
        txtNoDose.setText("");
        txtPrice.setText("");
        txtQty.setText("");
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        approveVaccine request = (approveVaccine)workRequestJTable.getValueAt(selectedRow, 0);
        if(request.getStatus().equals("Rejected") || request.getStatus().equals("Approved")){
            JOptionPane.showMessageDialog(this, "Vaccine already processed");
            return;
        }
     
        request.setStatus("Rejected");
        request.getVaccine().setStatus("Rejected");
        request.getVaccine().setMgQty(txtQty.getText());
        request.getVaccine().setNoOfDoses(Integer.parseInt(txtNoDose.getText()));
        request.getVaccine().setGap(Integer.parseInt(txtGap.getText()));
        populateTable();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void txtGapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGapActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(txtNoDose.getText())==1){
            txtGap.setText("0");
            txtGap.setEditable(false);
        }
        
        
    }//GEN-LAST:event_txtGapActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtGap;
    private javax.swing.JTextField txtNoDose;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables

    private boolean validate(String qty, String noDose, String gap, String price) {
        if(qty.length()<1){
            JOptionPane.showMessageDialog(this, "Please enter dosage quantity before approving");
            return false;
        }
        if(noDose.length()<1){
            JOptionPane.showMessageDialog(this, "Please enter number of doses before approving");
            return false;
        }
        if(gap.length()<1){
            JOptionPane.showMessageDialog(this, "Please enter gap between both doses before approving");
            return false;
        }
        if(price.length()<1){
            JOptionPane.showMessageDialog(this, "Please enter vaccine price before approving");
            return false;
        }
        return true;
    }
}
