

package ui.AdministrativeRole;

import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        //valueLabel.setText(enterprise.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        enterpriseLabel1 = new javax.swing.JLabel();
        valueLabel1 = new javax.swing.JLabel();
        onePanel = new javax.swing.JPanel();
        lblOrganizations = new javax.swing.JLabel();
        twoPanel = new javax.swing.JPanel();
        lblEmployees = new javax.swing.JLabel();
        threePanel = new javax.swing.JPanel();
        lblUsers = new javax.swing.JLabel();
        cardWorkPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(36, 47, 65));
        setMinimumSize(new java.awt.Dimension(1440, 848));
        setPreferredSize(new java.awt.Dimension(1440, 848));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(36, 47, 65));
        menuPanel.setMaximumSize(new java.awt.Dimension(200, 848));
        menuPanel.setMinimumSize(new java.awt.Dimension(200, 848));
        menuPanel.setPreferredSize(new java.awt.Dimension(200, 848));

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseLabel1.setText("EnterPrise :");

        valueLabel1.setForeground(new java.awt.Color(255, 255, 255));
        valueLabel1.setText("<value>");

        onePanel.setBackground(new java.awt.Color(36, 47, 65));
        onePanel.setPreferredSize(new java.awt.Dimension(200, 40));
        onePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onePanelMouseClicked(evt);
            }
        });

        lblOrganizations.setFont(new java.awt.Font("Optima", 1, 16)); // NOI18N
        lblOrganizations.setForeground(new java.awt.Color(255, 255, 255));
        lblOrganizations.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrganizations.setText("Manage Organizations");
        lblOrganizations.setMaximumSize(new java.awt.Dimension(180, 20));
        lblOrganizations.setMinimumSize(new java.awt.Dimension(180, 20));
        lblOrganizations.setPreferredSize(new java.awt.Dimension(180, 20));

        javax.swing.GroupLayout onePanelLayout = new javax.swing.GroupLayout(onePanel);
        onePanel.setLayout(onePanelLayout);
        onePanelLayout.setHorizontalGroup(
            onePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrganizations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        onePanelLayout.setVerticalGroup(
            onePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, onePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrganizations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        twoPanel.setBackground(new java.awt.Color(36, 47, 65));
        twoPanel.setPreferredSize(new java.awt.Dimension(200, 40));
        twoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoPanelMouseClicked(evt);
            }
        });

        lblEmployees.setFont(new java.awt.Font("Optima", 1, 16)); // NOI18N
        lblEmployees.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmployees.setText("Manage Employees");
        lblEmployees.setMaximumSize(new java.awt.Dimension(180, 20));
        lblEmployees.setMinimumSize(new java.awt.Dimension(180, 20));
        lblEmployees.setPreferredSize(new java.awt.Dimension(180, 20));

        javax.swing.GroupLayout twoPanelLayout = new javax.swing.GroupLayout(twoPanel);
        twoPanel.setLayout(twoPanelLayout);
        twoPanelLayout.setHorizontalGroup(
            twoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(twoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        twoPanelLayout.setVerticalGroup(
            twoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(twoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        threePanel.setBackground(new java.awt.Color(36, 47, 65));
        threePanel.setPreferredSize(new java.awt.Dimension(200, 40));
        threePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threePanelMouseClicked(evt);
            }
        });

        lblUsers.setFont(new java.awt.Font("Optima", 1, 16)); // NOI18N
        lblUsers.setForeground(new java.awt.Color(255, 255, 255));
        lblUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsers.setText("Manage Users");
        lblUsers.setMaximumSize(new java.awt.Dimension(180, 20));
        lblUsers.setMinimumSize(new java.awt.Dimension(180, 20));
        lblUsers.setPreferredSize(new java.awt.Dimension(180, 20));

        javax.swing.GroupLayout threePanelLayout = new javax.swing.GroupLayout(threePanel);
        threePanel.setLayout(threePanelLayout);
        threePanelLayout.setHorizontalGroup(
            threePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, threePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        threePanelLayout.setVerticalGroup(
            threePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(threePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(enterpriseLabel1)
                .addGap(5, 5, 5)
                .addComponent(valueLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(twoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(threePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(onePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {onePanel, threePanel, twoPanel});

        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel1)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(valueLabel1)))
                .addGap(75, 75, 75)
                .addComponent(onePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(twoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(threePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(602, 602, 602))
        );

        menuPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {onePanel, threePanel, twoPanel});

        add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cardWorkPanel.setBackground(new java.awt.Color(36, 47, 65));
        cardWorkPanel.setMinimumSize(new java.awt.Dimension(1240, 848));
        cardWorkPanel.setPreferredSize(new java.awt.Dimension(1240, 848));
        cardWorkPanel.setLayout(new java.awt.CardLayout());
        add(cardWorkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void twoPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoPanelMouseClicked
        // TODO add your handling code here:
        setColor(twoPanel);
        resetColor(new JPanel[]{onePanel,threePanel});
        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_twoPanelMouseClicked

    private void onePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onePanelMouseClicked
        // TODO add your handling code here:
        setColor(onePanel);
        resetColor(new JPanel[]{twoPanel,threePanel});
        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_onePanelMouseClicked

    private void threePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threePanelMouseClicked
        // TODO add your handling code here:
        setColor(threePanel);
        resetColor(new JPanel[]{onePanel,twoPanel});
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_threePanelMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardWorkPanel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel lblEmployees;
    private javax.swing.JLabel lblOrganizations;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel onePanel;
    private javax.swing.JPanel threePanel;
    private javax.swing.JPanel twoPanel;
    private javax.swing.JLabel valueLabel1;
    // End of variables declaration//GEN-END:variables
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(23,35,51));
    }
    private void resetColor(JPanel [] pane)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(36,47,65));
           
        }
    }
}
