/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.prescribeMedicine;
import javax.swing.JPanel;

/**
 *
 * @author vraj
 */
public class AddPrescriptionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPrescriptionJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem system;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount person;//userProcessContainer, enterprise, organization, system
    public AddPrescriptionJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, EcoSystem system, UserAccount account, UserAccount person) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
        this.enterprise = enterprise;
        this.organization = organization;
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMedList = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();

        jLabel1.setText("Medicine List");

        txtMedList.setColumns(20);
        txtMedList.setRows(5);
        jScrollPane1.setViewportView(txtMedList);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(btnSubmit)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(validate(txtMedList.getText())){
            UserAccount pharma = new UserAccount();
            prescribeMedicine pm = new prescribeMedicine();
            pm.setPerson(person);
            pm.setSender(account);
            Network cn = enterprise.getNetwork();
            for(Enterprise e : cn.getEnterpriseDirectory().getEnterpriseList()){
                if(e.getEnterpriseType() == EnterpriseType.Hospital){
                    for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                        for(UserAccount u : o.getUserAccountDirectory().getUserAccountList()){
                            if(u.getRole().toString().equals("Business.Role.PharmaRole")){
                                pm.setReceiver(u);
                                pharma = u;
                                break;
                            }
                        }
                    }
                }
            }
            pm.setMessage(person.getUsername());
            pm.setMedList(txtMedList.getText());
            pm.setStatus("Request");
            person.getWorkQueue().getWorkRequestList().add(pm);
            account.getWorkQueue().getWorkRequestList().add(pm);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtMedList;
    // End of variables declaration//GEN-END:variables

    private boolean validate(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
