/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.LabRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.LabOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.appointment;
import java.awt.Color;
//import java.net.PasswordAuthentication;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Properties;
import javax.mail.Session;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vraj
 */
public class LabAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private LabOrganization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private UserAccount userAccount;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    /**
     * Creates new form LabAreaJPanel
     */
    public LabAreaJPanel(JPanel userProcessContainer, UserAccount account, LabOrganization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        this.userAccount = account;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSubmit = new javax.swing.JButton();
        txtResult = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vitalYesRadio = new javax.swing.JRadioButton();
        vitalNoRadio = new javax.swing.JRadioButton();
        dosageYesRadio = new javax.swing.JRadioButton();
        coldYesRadio = new javax.swing.JRadioButton();
        tempYesRadio = new javax.swing.JRadioButton();
        dosageNoRadio = new javax.swing.JRadioButton();
        coldNoRadio = new javax.swing.JRadioButton();
        tempNoRadio = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        vitalSignBar = new javax.swing.JProgressBar();
        DosageBar = new javax.swing.JProgressBar();
        ColdBar = new javax.swing.JProgressBar();
        TemperatureBar = new javax.swing.JProgressBar();
        jLabel10 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jButtonSendReport = new javax.swing.JButton();
        separatorLine = new javax.swing.JSeparator();
        separatorLine1 = new javax.swing.JSeparator();
        separatorLine2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(36, 47, 65));
        setMinimumSize(new java.awt.Dimension(1440, 848));
        setPreferredSize(new java.awt.Dimension(1440, 848));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lab Testing Zone!");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 6, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Sender Email", "Receiver", "Status", "Result"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 78, 441, 113));

        btnSubmit.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 205, -1, -1));

        txtResult.setBackground(new java.awt.Color(36, 47, 65));
        txtResult.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        txtResult.setForeground(new java.awt.Color(255, 255, 255));
        txtResult.setBorder(null);
        txtResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultActionPerformed(evt);
            }
        });
        add(txtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 210, 250, -1));

        jLabel2.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Are the Vital Signs of the person completely normal ? ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 266, -1, -1));

        jLabel3.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Has the patient completed both the doses ?");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 303, 360, -1));

        jLabel4.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Does the patient have cold, cough ?");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 334, 360, -1));

        jLabel5.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Does the patient have a normal temperature ? ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 362, 360, -1));

        vitalYesRadio.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        vitalYesRadio.setForeground(new java.awt.Color(255, 255, 255));
        vitalYesRadio.setText("Yes");
        vitalYesRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitalYesRadioActionPerformed(evt);
            }
        });
        add(vitalYesRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 263, -1, -1));

        vitalNoRadio.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        vitalNoRadio.setForeground(new java.awt.Color(255, 255, 255));
        vitalNoRadio.setText("No");
        vitalNoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitalNoRadioActionPerformed(evt);
            }
        });
        add(vitalNoRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 263, -1, -1));

        dosageYesRadio.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        dosageYesRadio.setForeground(new java.awt.Color(255, 255, 255));
        dosageYesRadio.setText("Yes");
        dosageYesRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosageYesRadioActionPerformed(evt);
            }
        });
        add(dosageYesRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        coldYesRadio.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        coldYesRadio.setForeground(new java.awt.Color(255, 255, 255));
        coldYesRadio.setText("Yes");
        coldYesRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coldYesRadioActionPerformed(evt);
            }
        });
        add(coldYesRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 331, -1, -1));

        tempYesRadio.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        tempYesRadio.setForeground(new java.awt.Color(255, 255, 255));
        tempYesRadio.setText("Yes");
        tempYesRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempYesRadioActionPerformed(evt);
            }
        });
        add(tempYesRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 362, -1, -1));

        dosageNoRadio.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        dosageNoRadio.setForeground(new java.awt.Color(255, 255, 255));
        dosageNoRadio.setText("No");
        dosageNoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosageNoRadioActionPerformed(evt);
            }
        });
        add(dosageNoRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 300, -1, -1));

        coldNoRadio.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        coldNoRadio.setForeground(new java.awt.Color(255, 255, 255));
        coldNoRadio.setText("No");
        coldNoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coldNoRadioActionPerformed(evt);
            }
        });
        add(coldNoRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 331, -1, -1));

        tempNoRadio.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        tempNoRadio.setForeground(new java.awt.Color(255, 255, 255));
        tempNoRadio.setText("No");
        tempNoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempNoRadioActionPerformed(evt);
            }
        });
        add(tempNoRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 362, -1, -1));

        jLabel6.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Vital Signs : ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 412, -1, -1));

        jLabel7.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dosage : ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 444, -1, -1));

        jLabel8.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cold, cough : ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 470, -1, -1));

        jLabel9.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Temperature : ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 512, -1, -1));

        vitalSignBar.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        vitalSignBar.setForeground(new java.awt.Color(0, 255, 51));
        vitalSignBar.setBorder(null);
        add(vitalSignBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 412, -1, -1));

        DosageBar.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        DosageBar.setForeground(new java.awt.Color(0, 255, 51));
        DosageBar.setBorder(null);
        add(DosageBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 444, -1, -1));

        ColdBar.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        ColdBar.setForeground(new java.awt.Color(0, 255, 51));
        ColdBar.setBorder(null);
        add(ColdBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 470, -1, -1));

        TemperatureBar.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        TemperatureBar.setForeground(new java.awt.Color(0, 255, 51));
        TemperatureBar.setBorder(null);
        add(TemperatureBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 512, -1, -1));

        jLabel10.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Final Report : ");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 412, -1, -1));

        jProgressBar1.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jProgressBar1.setForeground(new java.awt.Color(0, 255, 51));
        jProgressBar1.setBorder(null);
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 412, 308, -1));

        jLabel11.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Result : ");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 475, -1, -1));

        jTextField1.setBackground(new java.awt.Color(36, 47, 65));
        jTextField1.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 296, -1));

        jButton1.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jButton1.setText("Generate Report!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 544, -1, -1));

        jLabel12.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("To: ");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 596, 72, -1));

        txtTo.setBackground(new java.awt.Color(36, 47, 65));
        txtTo.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        txtTo.setForeground(new java.awt.Color(255, 255, 255));
        txtTo.setBorder(null);
        txtTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtToActionPerformed(evt);
            }
        });
        add(txtTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 591, 206, -1));

        jTextArea1.setBackground(new java.awt.Color(36, 47, 65));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane2.setViewportView(jTextArea1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 639, -1, 148));

        jLabel13.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Report : ");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 648, -1, -1));

        jButtonSendReport.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        jButtonSendReport.setText("Send Report!");
        jButtonSendReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendReportActionPerformed(evt);
            }
        });
        add(jButtonSendReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 805, -1, -1));

        separatorLine.setForeground(new java.awt.Color(255, 255, 255));
        separatorLine.setMinimumSize(new java.awt.Dimension(1, 12));
        separatorLine.setPreferredSize(new java.awt.Dimension(1, 12));
        add(separatorLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 220, 10));

        separatorLine1.setForeground(new java.awt.Color(255, 255, 255));
        separatorLine1.setMinimumSize(new java.awt.Dimension(1, 12));
        separatorLine1.setPreferredSize(new java.awt.Dimension(1, 12));
        add(separatorLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 220, 10));

        separatorLine2.setForeground(new java.awt.Color(255, 255, 255));
        separatorLine2.setMinimumSize(new java.awt.Dimension(1, 12));
        separatorLine2.setPreferredSize(new java.awt.Dimension(1, 12));
        add(separatorLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 220, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(!txtResult.getText().equals(jTextField1.getText())){
            JOptionPane.showMessageDialog(this, "Please input valid report");
            return;
        }
        int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        appointment request = (appointment)jTable1.getValueAt(selectedRow, 0);
     System.out.println("1");
        request.setTestResult(txtResult.getText());
        System.out.println(txtResult.getText());
        System.out.println("2");
        JOptionPane.showMessageDialog(this, "Request tested");
        populateTable();
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void vitalYesRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitalYesRadioActionPerformed
        // TODO add your handling code here:
        if(vitalNoRadio.isSelected()){
            vitalNoRadio.setSelected(false);
        }
        int internalvalue = 100;
        vitalSignBar.setValue(internalvalue);
        
       
    }//GEN-LAST:event_vitalYesRadioActionPerformed

    private void dosageNoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosageNoRadioActionPerformed
        // TODO add your handling code here:
        if(dosageYesRadio.isSelected()){
            dosageYesRadio.setSelected(false);
        }
        int value = 0;
        DosageBar.setValue(value);
    }//GEN-LAST:event_dosageNoRadioActionPerformed

    private void vitalNoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitalNoRadioActionPerformed
        if(vitalYesRadio.isSelected()){
            vitalYesRadio.setSelected(false);
        }
        int value = 0;
        vitalSignBar.setValue(value);

        
    }//GEN-LAST:event_vitalNoRadioActionPerformed

    private void dosageYesRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosageYesRadioActionPerformed
        // TODO add your handling code here:
        if(dosageNoRadio.isSelected()){
            dosageNoRadio.setSelected(false);
        }
        int internalvalue = 100;
        DosageBar.setValue(internalvalue);
        
    }//GEN-LAST:event_dosageYesRadioActionPerformed

    private void coldYesRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coldYesRadioActionPerformed
        // TODO add your handling code here:
        if(coldNoRadio.isSelected()){
            coldNoRadio.setSelected(false);
        }
        int internalvalue = 100;
        ColdBar.setValue(internalvalue);
        
        
    }//GEN-LAST:event_coldYesRadioActionPerformed

    private void coldNoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coldNoRadioActionPerformed
        // TODO add your handling code here:
         if(coldYesRadio.isSelected()){
            coldYesRadio.setSelected(false);
        }
        int value = 0;
        ColdBar.setValue(value);
    }//GEN-LAST:event_coldNoRadioActionPerformed

    private void tempYesRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempYesRadioActionPerformed
        // TODO add your handling code here:
        if(tempNoRadio.isSelected()){
            tempNoRadio.setSelected(false);
        }
        int internalvalue = 100;
        TemperatureBar.setValue(internalvalue);
        
    }//GEN-LAST:event_tempYesRadioActionPerformed

    private void tempNoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempNoRadioActionPerformed
        // TODO add your handling code here:
         if(tempYesRadio.isSelected()){
            tempYesRadio.setSelected(false);
        }
        int value = 0;
        TemperatureBar.setValue(value);
    }//GEN-LAST:event_tempNoRadioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int vitals = vitalSignBar.getValue()/4;
        int cold = ColdBar.getValue()/4;
        int dosage = DosageBar.getValue()/4;
        int temp = TemperatureBar.getValue()/4;
        
        int finalResult = vitals + cold + dosage + temp;
        
        jProgressBar1.setValue(finalResult);
        if(finalResult == 100){
            jProgressBar1.setStringPainted(true);
            jProgressBar1.setForeground(Color.white);
            jProgressBar1.setBackground(Color.green);
           
            
            jTextField1.setText("Approved !");
        } else if(finalResult >= 50 && finalResult < 100){
            jProgressBar1.setForeground(Color.YELLOW);
            jTextField1.setText("Needs Monitoring");
        }else if (finalResult < 50){
            jProgressBar1.setForeground(Color.RED);
            jTextField1.setText("Danger!");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultActionPerformed

    private void txtToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToActionPerformed

    private void jButtonSendReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendReportActionPerformed
        // TODO add your handling code here:
        String toEmail = txtTo.getText();
        String fromEmail = "nuccfall2021@gmail.com";
        String fromEmailPassword = "nuccnucc";
        String subject = "Report from NUCC";
        
        Properties props = new Properties();
        props.put("mail.smtp.user","username"); 
        props.put("mail.smtp.host", "smtp.gmail.com"); 
        props.put("mail.smtp.port", "25"); 
        props.put("mail.debug", "true"); 
        props.put("mail.smtp.auth", "true"); 
        props.put("mail.smtp.starttls.enable","true"); 
        props.put("mail.smtp.EnableSSL.enable","true");

        props.setProperty("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");   
        props.setProperty("mail.smtp.socketFactory.fallback", "false");   
        props.setProperty("mail.smtp.port", "465");   
        props.setProperty("mail.smtp.socketFactory.port", "465");
        
        Session session = Session.getDefaultInstance(props , new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication(fromEmail , fromEmailPassword);
            }
        });
        populateTable();
        
        try{
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(fromEmail));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(toEmail));
            message.setSubject(subject);
            message.setText(jTextArea1.getText());
            Transport.send(message);
        }catch(Exception e){
            System.out.print(e);
        }
        
    }//GEN-LAST:event_jButtonSendReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ColdBar;
    private javax.swing.JProgressBar DosageBar;
    private javax.swing.JProgressBar TemperatureBar;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JRadioButton coldNoRadio;
    private javax.swing.JRadioButton coldYesRadio;
    private javax.swing.JRadioButton dosageNoRadio;
    private javax.swing.JRadioButton dosageYesRadio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSendReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JSeparator separatorLine;
    private javax.swing.JSeparator separatorLine1;
    private javax.swing.JSeparator separatorLine2;
    private javax.swing.JRadioButton tempNoRadio;
    private javax.swing.JRadioButton tempYesRadio;
    private javax.swing.JTextField txtResult;
    private javax.swing.JTextField txtTo;
    private javax.swing.JRadioButton vitalNoRadio;
    private javax.swing.JProgressBar vitalSignBar;
    private javax.swing.JRadioButton vitalYesRadio;
    // End of variables declaration//GEN-END:variables
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
            if(request instanceof appointment){
            row[0] = request;
            row[1] = request.getSender().getEmployee().getName();
            String email = ((appointment) request).getEmail();
            row[2] = email;
            row[3] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[4] = request.getStatus();
            String result = ((appointment) request).getTestResult();
            row[5] = result;
            
            
            model.addRow(row);
        }
        }
    }
}
